### ISSUE TITLE
Router's on method is declared as any

### ISSUE THREAD

**Issue by XVincentX** [turist-cloud/micri#17]
I do not know the reason, but `on` method is marked as `any` in the generated d.ts file that's in the package

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1416224/68332349-445c0180-009c-11ea-9404-bc4767088182.png">

**Comment by OlliV** [comment]
Probably just a mistake. I can't think of any good reason. Thanks for reporting.

**Comment by XVincentX** [comment]
@OlliV I just realised *YOU WERE YESTERDAY AT THE ROMEJS MEETUP I WAS SPEAKING* :trollface:
