### ISSUE TITLE
TS2307: Cannot find module 'raw-body'.

### ISSUE THREAD

**Issue by pizzafox** [turist-cloud/micri#24]
micri 4.1.0 has this error causing my TypeScript builds to fail:

```
##[error]node_modules/micri/dist/errors.d.ts(1,30): error TS2307: Cannot find module 'raw-body'.
```

**Comment by OlliV** [comment]
Thanks for reporting. A workaround is to install `raw-body` separately to get the typings.

**Comment by OlliV** [comment]
Published new versions fixing the issue:
- https://github.com/turist-cloud/micri/releases/tag/3.0.1
- https://github.com/turist-cloud/micri/releases/tag/4.1.2
